# Generated by Django 5.2.4 on 2025-07-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_order_delivery_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unique_order_code',
        ),
    ]
